### ISSUE TITLE
请问一下这个加密方式是怎么找到的？

### ISSUE THREAD

**Issue by zhy8388608** [helloseewo/helloseewo.github.io#1]

**Comment by Sycamore0** [comment]
万能的群友（
可惜当前官方修复了

**Comment by Sycamore0** [comment]
现在正在研究新的加密方式

**Comment by Sycamore0** [comment]
该方法已被修复。
而且这个公布会导致之后的研究更为困难。

**Comment by Sycamore0** [comment]
如果可以的话，你能给我提供一个新版的激活码二维码的链接吗？
![firefly](https://github.com/helloseewo/helloseewo.github.io/assets/64587684/19357edd-3b95-4f4b-a2e4-1d03f64f3971)

**Comment by zhy8388608** [comment]
能否联系QQ？2310608308

**Comment by Sycamore0** [comment]
> 当然。能否联系QQ？2310608308

qq就算了，给孩子留点隐私吧（
![1c0ba0e3ce66c875df7b7039e8978dc1](https://github.com/helloseewo/helloseewo.github.io/assets/64587684/bfb7e53b-beb3-4a0e-a85e-8a5b3dbc409a)

**Comment by zhy8388608** [comment]
那就telegram吧。zhy8388608

**Comment by zhy8388608** [comment]
我开发了一个新版密码计算工具，想跟您交流一下。

**Comment by zhy8388608** [comment]
如果我没猜错的话，您应该是获取到了生成二维码的js文件。而这个文件应该是来自安卓希沃一体机的。

**Comment by Sycamore0** [comment]
> Reference i

前半句对了，但是后半句错了

**Comment by zhy8388608** [comment]
有趣，这个js文件是您抓包找到的吗？
